### ISSUE TITLE
this plugin

### ISSUE THREAD

**Issue by YazdanXos** [grzegorz2047/NukkitSurvivalGames#1]
how to download and use this plugin ?

**Comment by grzegorz2047** [comment]
Sadly i didnt convert my bukkit plugin into nukkit version of it so currently lacks of implementation. It supposed to be based on https://github.com/grzegorz2047/SurvivalGames-Bukkit/tree/master/src/pl/grzegorz2047/survivalgames
Currently nukkit plugin is not in usable state, sorry.
